<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Fast.Admin 应用核心模块库。</Description>
    </PropertyGroup>

    <ItemGroup>
        <None Update="Assets\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Fast.Cache" />
        <PackageReference Include="Fast.DependencyInjection" />
        <PackageReference Include="Fast.DynamicApplication" />
        <PackageReference Include="Fast.IaaS" />
        <PackageReference Include="Fast.JwtBearer" />
        <PackageReference Include="Fast.Logging" />
        <PackageReference Include="Fast.OpenApi" />
        <PackageReference Include="Fast.NET.Core" />
        <PackageReference Include="Fast.Serialization.Newtonsoft.Json" />
        <PackageReference Include="Fast.Swagger" />
        <PackageReference Include="Fast.UnifyResult" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AlibabaCloud.SDK.Dysmsapi20180501" />
        <PackageReference Include="AlipaySDKNet.Standard" />
        <PackageReference Include="SKIT.FlurlHttpClient.Wechat.Api" />
        <PackageReference Include="SKIT.FlurlHttpClient.Wechat.TenpayV3" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" />
        <PackageReference Include="MiniExcel" />
        <PackageReference Include="ToolGood.Words.Pinyin" />
        <PackageReference Include="ZXing.Net" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SixLabors.Fonts" />
        <PackageReference Include="SixLabors.ImageSharp" />
        <PackageReference Include="SixLabors.ImageSharp.Drawing" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)src\Domain\Center\Entity\Fast.Center.Entity.csproj" />
        <ProjectReference Include="$(SolutionDir)src\Domain\CenterLog\Entity\Fast.CenterLog.Entity.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <None Update="coresettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="coresettings.Development.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="dbsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="dbsettings.Development.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>