/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FaFooter: typeof import('@/components/footer/index.vue')['default']
    FaIcon: typeof import('@/components/icon/index.vue')['default']
    FaLoading: typeof import('@/components/loading/index.vue')['default']
    FaLoadingPage: typeof import('@/components/loadingPage/index.vue')['default']
    FaOverlay: typeof import('@/components/overlay/index.vue')['default']
    FaPopup: typeof import('@/components/popup/index.vue')['default']
    FaTabBar: typeof import('@/components/tabBar/index.vue')['default']
    FaWatermark: typeof import('@/components/watermark/index.vue')['default']
    WdBadge: typeof import('wot-design-uni/components/wd-badge/wd-badge.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdCheckbox: typeof import('wot-design-uni/components/wd-checkbox/wd-checkbox.vue')['default']
    WdConfigProvider: typeof import('wot-design-uni/components/wd-config-provider/wd-config-provider.vue')['default']
    WdForm: typeof import('wot-design-uni/components/wd-form/wd-form.vue')['default']
    WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['default']
    WdInput: typeof import('wot-design-uni/components/wd-input/wd-input.vue')['default']
    WdMessageBox: typeof import('wot-design-uni/components/wd-message-box/wd-message-box.vue')['default']
    WdNotify: typeof import('wot-design-uni/components/wd-notify/wd-notify.vue')['default']
    WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['default']
    WdToast: typeof import('wot-design-uni/components/wd-toast/wd-toast.vue')['default']
    WdWatermark: typeof import('wot-design-uni/components/wd-watermark/wd-watermark.vue')['default']
  }
}
