/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Auto-generated by fast component-auto-import
// Generated by fast-vite-plugins
// Do not edit this file manually

import type { App } from "vue";

import AccountSelectPage from "./AccountSelectPage/index.vue";
export { AccountSelectPage };
export type AccountSelectPageInstance = InstanceType<typeof AccountSelectPage>;
import ApplicationSelect from "./ApplicationSelect/index.vue";
export { ApplicationSelect };
export type ApplicationSelectInstance = InstanceType<typeof ApplicationSelect>;
import ApplicationTree from "./ApplicationTree/index.vue";
export { ApplicationTree };
export type ApplicationTreeInstance = InstanceType<typeof ApplicationTree>;
import ColorPicker from "./ColorPicker/index.vue";
export { ColorPicker };
export type ColorPickerInstance = InstanceType<typeof ColorPicker>;
import Editor from "./Editor/index.vue";
export { Editor };
export type EditorInstance = InstanceType<typeof Editor>;
import FastTable from "./FastTable/index.tsx";
export { FastTable };
export type FastTableInstance = InstanceType<typeof FastTable>;
import Footer from "./Footer/index.vue";
export { Footer };
export type FooterInstance = InstanceType<typeof Footer>;
import IconSelect from "./IconSelect/index.vue";
export { IconSelect };
export type IconSelectInstance = InstanceType<typeof IconSelect>;
import Loading from "./Loading/index.vue";
export { Loading };
export type LoadingInstance = InstanceType<typeof Loading>;
import MerchantSelect from "./MerchantSelect/index.vue";
export { MerchantSelect };
export type MerchantSelectInstance = InstanceType<typeof MerchantSelect>;
import ModuleSelect from "./ModuleSelect/index.vue";
export { ModuleSelect };
export type ModuleSelectInstance = InstanceType<typeof ModuleSelect>;
import RadioGroup from "./RadioGroup/index.vue";
export { RadioGroup };
export type RadioGroupInstance = InstanceType<typeof RadioGroup>;
import Tag from "./Tag/index.vue";
export { Tag };
export type TagInstance = InstanceType<typeof Tag>;
import TenantSelectPage from "./TenantSelectPage/index.vue";
export { TenantSelectPage };
export type TenantSelectPageInstance = InstanceType<typeof TenantSelectPage>;
import Tendril from "./Tendril/index.vue";
export { Tendril };
export type TendrilInstance = InstanceType<typeof Tendril>;
import Text from "./Text/index.vue";
export { Text };
export type TextInstance = InstanceType<typeof Text>;
import Watermark from "./Watermark/index.vue";
export { Watermark };
export type WatermarkInstance = InstanceType<typeof Watermark>;

/** 自动注册所有组件 */
export function registerComponents(app: App): void {
	app.component(AccountSelectPage.name, AccountSelectPage);
	app.component(ApplicationSelect.name, ApplicationSelect);
	app.component(ApplicationTree.name, ApplicationTree);
	app.component(ColorPicker.name, ColorPicker);
	app.component(Editor.name, Editor);
	app.component(FastTable.name, FastTable);
	app.component(Footer.name, Footer);
	app.component(IconSelect.name, IconSelect);
	app.component(Loading.name, Loading);
	app.component(MerchantSelect.name, MerchantSelect);
	app.component(ModuleSelect.name, ModuleSelect);
	app.component(RadioGroup.name, RadioGroup);
	app.component(Tag.name, Tag);
	app.component(TenantSelectPage.name, TenantSelectPage);
	app.component(Tendril.name, Tendril);
	app.component(Text.name, Text);
	app.component(Watermark.name, Watermark);
}

