packages:
    - "."

storeDir: .pnpm-store

minimumReleaseAge: 0

patchedDependencies:
    element-plus: patches/element-plus.patch

allowBuilds:
    "@parcel/watcher": true
    es5-ext: true
    unrs-resolver: true
