// For this project development
// Auto-generated by fast component-auto-import
// Generated by fast-vite-plugins
// Do not edit this file manually

import "@vue/runtime-core";

// GlobalComponents for Volar
declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		AccountSelectPage: (typeof import("../src/components/AccountSelectPage/index.vue"))["default"];
		ApplicationSelect: (typeof import("../src/components/ApplicationSelect/index.vue"))["default"];
		ApplicationTree: (typeof import("../src/components/ApplicationTree/index.vue"))["default"];
		CitySelect: (typeof import("../src/components/CitySelect/index.vue"))["default"];
		ColorPicker: (typeof import("../src/components/ColorPicker/index.vue"))["default"];
		Editor: (typeof import("../src/components/Editor/index.vue"))["default"];
		EmployeeDialogSelect: (typeof import("../src/components/EmployeeDialogSelect/index.vue"))["default"];
		EmployeeSelectPage: (typeof import("../src/components/EmployeeSelectPage/index.vue"))["default"];
		FastTable: (typeof import("../src/components/FastTable/index.tsx"))["default"];
		Footer: (typeof import("../src/components/Footer/index.vue"))["default"];
		IconSelect: (typeof import("../src/components/IconSelect/index.vue"))["default"];
		Loading: (typeof import("../src/components/Loading/index.vue"))["default"];
		MerchantSelect: (typeof import("../src/components/MerchantSelect/index.vue"))["default"];
		ModuleSelect: (typeof import("../src/components/ModuleSelect/index.vue"))["default"];
		ProvinceSelect: (typeof import("../src/components/ProvinceSelect/index.vue"))["default"];
		RadioGroup: (typeof import("../src/components/RadioGroup/index.vue"))["default"];
		RegionSelect: (typeof import("../src/components/RegionSelect/index.vue"))["default"];
		Tag: (typeof import("../src/components/Tag/index.vue"))["default"];
		TenantSelectPage: (typeof import("../src/components/TenantSelectPage/index.vue"))["default"];
		Tendril: (typeof import("../src/components/Tendril/index.vue"))["default"];
		Text: (typeof import("../src/components/Text/index.vue"))["default"];
		Watermark: (typeof import("../src/components/Watermark/index.vue"))["default"];
	}
}

export {};
