// For this project development
// Auto-generated by fast component-auto-import
// Generated by fast-vite-plugins
// Do not edit this file manually

import "@vue/runtime-core";

// GlobalComponents for Volar
declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		AccountSelectPage: (typeof import("../src/components/AccountSelectPage/index"))["default"];
		ApplicationSelect: (typeof import("../src/components/ApplicationSelect/index"))["default"];
		ApplicationTree: (typeof import("../src/components/ApplicationTree/index"))["default"];
		Editor: (typeof import("../src/components/Editor/index"))["default"];
		FastTable: (typeof import("../src/components/FastTable/index"))["default"];
		Footer: (typeof import("../src/components/Footer/index"))["default"];
		Loading: (typeof import("../src/components/Loading/index"))["default"];
		ModuleSelect: (typeof import("../src/components/ModuleSelect/index"))["default"];
		RadioGroup: (typeof import("../src/components/RadioGroup/index"))["default"];
		Tag: (typeof import("../src/components/Tag/index"))["default"];
		TenantSelectPage: (typeof import("../src/components/TenantSelectPage/index"))["default"];
		Tendril: (typeof import("../src/components/Tendril/index"))["default"];
		Watermark: (typeof import("../src/components/Watermark/index"))["default"];
	}
}

export {};
